stages:
  - verify
  - deploy
  - notify

deploy_to_server:
  stage: deploy
  image: alpine:3
  script:
    - apk update && apk add openssh-client rsync
    - chmod 400 ${DEPLOY_SSH_KEY}
    - /usr/bin/rsync -avz --exclude .git --exclude ${DEPLOY_SSH_KEY} -e "ssh -i ${DEPLOY_SSH_KEY} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" . ${RSYNC_ENDPOINT}

notify_success:
  stage: notify
  image: alpine:latest
  before_script:
    - apk update && apk add curl
  when: on_success
  allow_failure: true
  script:
    - project="${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
    - curl -s --form-string "token=${PUSHOVER_TOKEN}"
              --form-string "user=${PUSHOVER_USER_TOKEN}"
              --form-string "url=${CI_PIPELINE_URL}"
              --form-string "priority=0"
              --form-string "message=Pipeline success for ${project} on ${CI_COMMIT_REF_NAME}"
              https://api.pushover.net/1/messages.json

notify_fail:
  stage: notify
  image: alpine:latest
  before_script:
    - apk update && apk add curl
  when: on_failure
  allow_failure: true
  script:
    - project="${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
    - curl -s --form-string "token=${PUSHOVER_TOKEN}"
              --form-string "user=${PUSHOVER_USER_TOKEN}"
              --form-string "url=${CI_JOB_URL}"
              --form-string "priority=1"
              --form-string "message=Pipeline failure for ${project} on ${CI_COMMIT_REF_NAME}"
              https://api.pushover.net/1/messages.json
